"""cancan CLI entrypoint (library-owned).

目标 / Goal:
- controllersrv 在宿主机运行：提供 start/stop/status
  controllersrv runs on host: start/stop/status
- 集群通过 {engine} compose 启动/关闭：提供 cluster up/down
  cluster via {engine} compose: cluster up/down
- adminops 前端构建为静态 SPA 并发布到使用方工作区的 Caddy 静态目录
    Build adminops frontend into static assets and publish to consumer workspace's Caddy static dir

重要说明 / Important Notes:
- 该 CLI 属于 libs（cancan_microstack），使用方仓库不应长期保存框架脚本。
    This CLI belongs to libs (cancan_microstack); consumer repos should not keep framework scripts.
- 所有路径均通过动态计算，禁止硬编码绝对路径。
  All paths are resolved dynamically; do NOT hardcode absolute paths.
"""
import argparse
import os
import shutil
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional


def _find_repo_root(start: Path) -> Path:
    """尝试从 start 向上查找使用方仓库根目录 / Try to locate consumer repo root.

    查找标记 / Markers:
    - compose.cancan.yml
    - docker-compose.yml
    - pyproject.toml
    """

    start = start.resolve()
    candidates = [start, *start.parents]

    for base in candidates:
        if (base / "compose.cancan.yml").exists():
            return base
        if (base / "docker-compose.yml").exists():
            return base
        if (base / "pyproject.toml").exists():
            return base

    return start


def _runtime_dir(repo_root: Path) -> Path:
    """运行时目录 / Runtime dir."""

    runtime_dir = repo_root / ".runtime"
    runtime_dir.mkdir(parents=True, exist_ok=True)
    return runtime_dir


def _pid_file(repo_root: Path) -> Path:
    """controllersrv PID 文件路径 / controllersrv PID file path."""

    return _runtime_dir(repo_root) / "controllersrv.pid"


def _log_file(repo_root: Path) -> Path:
    """controllersrv 日志文件路径 / controllersrv log file path."""

    return _runtime_dir(repo_root) / "controllersrv.log"


def _is_process_alive(pid: int) -> bool:
    """判断进程是否存在 / Check whether a process exists."""

    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def _read_pid(repo_root: Path) -> Optional[int]:
    """读取 PID / Read PID."""

    pid_path = _pid_file(repo_root)
    if not pid_path.exists():
        return None

    try:
        pid = int(pid_path.read_text(encoding="utf-8").strip())
    except Exception:
        return None

    return pid


def controllersrv_status(repo_root: Path) -> int:
    """打印 controllersrv 状态 / Print controllersrv status."""

    pid = _read_pid(repo_root)
    if pid is None:
        print("controllersrv: stopped (no pid file)")
        return 1

    if _is_process_alive(pid):
        print(f"controllersrv: running (pid={pid})")
        return 0

    print(f"controllersrv: stale pid file (pid={pid})")
    return 2


def controllersrv_start(repo_root: Path, host: str, port: int) -> int:
    """启动 controllersrv（后台）/ Start controllersrv in background."""

    pid = _read_pid(repo_root)
    if pid is not None and _is_process_alive(pid):
        print(f"controllersrv already running (pid={pid})")
        return 0

    # 清理陈旧 pid 文件 / Remove stale pid file
    try:
        _pid_file(repo_root).unlink(missing_ok=True)
    except Exception:
        pass

    wrapper_script = repo_root / "cmd" / "controllersrv" / "run.py"
    if not wrapper_script.exists():
        print(f"controllersrv wrapper not found: {wrapper_script}")
        print("Hint: in a consumer repo, cmd wrappers are usually generated by cancan build.")
        return 2

    log_path = _log_file(repo_root)
    log_fp = open(log_path, "a", encoding="utf-8")

    # 使用当前解释器启动（建议在 venv 下运行本脚本）
    # Start using current interpreter (recommended: run this script under venv)
    cmd = [sys.executable, "-u", str(wrapper_script)]

    env = os.environ.copy()
    env.setdefault("PYTHONUNBUFFERED", "1")

    # 控制 host/port 通过环境变量传递。
    # Pass host/port via env.
    env["CONTROLLERSRV_HOST_BIND"] = host
    env["CONTROLLERSRV_PORT_BIND"] = str(port)

    proc = subprocess.Popen(
        cmd,
        cwd=str(repo_root),
        env=env,
        stdout=log_fp,
        stderr=log_fp,
        start_new_session=True,
    )

    _pid_file(repo_root).write_text(str(proc.pid), encoding="utf-8")
    print(f"controllersrv started (pid={proc.pid}) log={log_path}")
    return 0


def controllersrv_stop(repo_root: Path, timeout_seconds: int = 10) -> int:
    """停止 controllersrv / Stop controllersrv."""

    pid = _read_pid(repo_root)
    if pid is None:
        print("controllersrv already stopped (no pid file)")
        return 0

    if not _is_process_alive(pid):
        print(f"controllersrv already stopped (pid={pid})")
        try:
            _pid_file(repo_root).unlink(missing_ok=True)
        except Exception:
            pass
        return 0

    print(f"Stopping controllersrv (pid={pid}) ...")
    try:
        os.kill(pid, signal.SIGTERM)
    except ProcessLookupError:
        _pid_file(repo_root).unlink(missing_ok=True)
        print("controllersrv stopped")
        return 0

    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if not _is_process_alive(pid):
            _pid_file(repo_root).unlink(missing_ok=True)
            print("controllersrv stopped")
            return 0
        time.sleep(0.2)

    print("controllersrv did not stop in time; sending SIGKILL")
    try:
        os.kill(pid, signal.SIGKILL)
    except ProcessLookupError:
        pass

    _pid_file(repo_root).unlink(missing_ok=True)
    return 0


def _run_compose(repo_root: Path, compose_engine: str, compose_file: Path, args: list[str]) -> int:
    """运行 compose 命令 / Run compose command."""

    if compose_engine not in {"podman", "docker"}:
        print(f"Unsupported compose engine: {compose_engine}")
        return 2

    cmd = [compose_engine, "compose", "-f", str(compose_file), *args]
    print("Running:", " ".join(cmd))

    proc = subprocess.run(cmd, cwd=str(repo_root))
    return int(proc.returncode)


def cluster_up(repo_root: Path, compose_engine: str, compose_file: Path) -> int:
    """启动集群 / Bring up the cluster."""

    rc = controllersrv_start(repo_root=repo_root, host="0.0.0.0", port=22100)
    if rc != 0:
        return rc

    return _run_compose(repo_root, compose_engine, compose_file, ["up", "-d"])


def cluster_down(repo_root: Path, compose_engine: str, compose_file: Path, keep_controllersrv: bool) -> int:
    """关闭集群 / Bring down the cluster."""

    rc = _run_compose(repo_root, compose_engine, compose_file, ["down"])
    if keep_controllersrv:
        return rc

    stop_rc = controllersrv_stop(repo_root)
    return rc if rc != 0 else stop_rc


def adminops_build_and_publish(repo_root: Path, admin_root: Path, output_dir: Path) -> int:
    """Build adminops and publish to output directory.

        - 构建 adminops 前端工程
            Build the adminops frontend project
        - 拷贝 dist 到使用方工作区的 Caddy 静态目录
            Copy dist into consumer workspace's Caddy static dir
    """

    if not admin_root.exists():
        print(f"adminops UI source not found: {admin_root}")
        return 2

    pnpm = shutil.which("pnpm")
    if not pnpm:
        print("pnpm not found in PATH")
        return 2

    print(f"Building adminops UI at: {admin_root}")
    build_proc = subprocess.run([pnpm, "-C", str(admin_root), "build"], check=False)
    if build_proc.returncode != 0:
        return int(build_proc.returncode)

    dist_dir = admin_root / "dist"
    if not dist_dir.exists():
        print(f"Build output not found: {dist_dir}")
        return 2

    output_dir.parent.mkdir(parents=True, exist_ok=True)
    if output_dir.exists():
        shutil.rmtree(output_dir)

    shutil.copytree(dist_dir, output_dir)
    print(f"Published adminops to: {output_dir}")
    print("Note: output directory is intended to be git-ignored.")
    return 0


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="cancan", add_help=True)

    parser.add_argument(
        "--repo-root",
        default=os.getenv("CANCAN_REPO_ROOT", ""),
        help="consumer repo root / 使用方仓库根目录（默认自动探测）",
    )

    parser.add_argument(
        "--engine",
        default=os.getenv("CANCAN_COMPOSE_ENGINE", "podman"),
        choices=["podman", "docker"],
        help="compose engine / compose 引擎（默认 podman）",
    )

    parser.add_argument(
        "--compose-file",
        default=os.getenv("CANCAN_COMPOSE_FILE", ""),
        help="compose file path / compose 文件路径（默认 repo_root/compose.cancan.yml）",
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    # controllersrv
    controllersrv_parser = subparsers.add_parser("controllersrv", help="controllersrv lifecycle")
    controllersrv_sub = controllersrv_parser.add_subparsers(dest="action", required=True)

    start_parser = controllersrv_sub.add_parser("start", help="start controllersrv")
    start_parser.add_argument("--host", default="0.0.0.0")
    start_parser.add_argument("--port", type=int, default=22100)

    stop_parser = controllersrv_sub.add_parser("stop", help="stop controllersrv")
    stop_parser.add_argument("--timeout", type=int, default=10)

    controllersrv_sub.add_parser("status", help="status controllersrv")

    # cluster
    cluster_parser = subparsers.add_parser("cluster", help="cluster up/down")
    cluster_sub = cluster_parser.add_subparsers(dest="action", required=True)

    cluster_sub.add_parser("up", help="compose up -d with controllersrv")

    down_parser = cluster_sub.add_parser("down", help="compose down and stop controllersrv")
    down_parser.add_argument(
        "--keep-controllersrv",
        action="store_true",
        help="do not stop controllersrv / 不停止 controllersrv",
    )

    # adminops
    admin_parser = subparsers.add_parser("adminops", help="adminops build/publish")
    admin_sub = admin_parser.add_subparsers(dest="action", required=True)

    build_parser = admin_sub.add_parser("build", help="build adminops and publish to Caddy dir")
    build_parser.add_argument(
        "--admin-root",
        default=os.getenv("CANCAN_ADMIN_ROOT", ""),
        help="adminops frontend root / 前端工程根目录（默认 repo_root 的同级目录）",
    )
    build_parser.add_argument(
        "--output-dir",
        default=os.getenv("CANCAN_ADMIN_OUTPUT_DIR", ""),
        help="publish output dir / 发布输出目录（默认 repo_root/builds/caddy/www/adminops）",
    )

    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = _parse_args(argv)

    if args.repo_root:
        repo_root = Path(args.repo_root).expanduser().absolute()
    else:
        repo_root = _find_repo_root(Path.cwd())

    compose_file = Path(args.compose_file).expanduser().absolute() if args.compose_file else (repo_root / "compose.cancan.yml")

    if args.command == "controllersrv":
        if args.action == "start":
            return controllersrv_start(repo_root=repo_root, host=args.host, port=args.port)
        if args.action == "stop":
            return controllersrv_stop(repo_root=repo_root, timeout_seconds=args.timeout)
        if args.action == "status":
            return controllersrv_status(repo_root)

    if args.command == "cluster":
        if args.action == "up":
            return cluster_up(repo_root=repo_root, compose_engine=args.engine, compose_file=compose_file)
        if args.action == "down":
            return cluster_down(
                repo_root=repo_root,
                compose_engine=args.engine,
                compose_file=compose_file,
                keep_controllersrv=bool(args.keep_controllersrv),
            )

    if args.command == "adminops":
        if args.action == "build":
            admin_root = (
                Path(args.admin_root).expanduser().absolute()
                if args.admin_root
                else repo_root.parent.absolute()
            )
            output_dir = (
                Path(args.output_dir).expanduser().absolute()
                if args.output_dir
                else (repo_root / "builds" / "caddy" / "www" / "adminops")
            )
            return adminops_build_and_publish(repo_root=repo_root, admin_root=admin_root, output_dir=output_dir)

    print("Unknown command")
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
